version: '2.1'

services:

  report-db:
    container_name: report-db
    build: ./project/db
    ports:
      - 5435:5432 # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  report-service:
    container_name: report-service
    build: ./
    expose:
      - 5000
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@report-db:5432/report_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@report-db:5432/report_test
    depends_on:
      report-db:
        condition: service_healthy
    links:
      - report-db
    command: gunicorn -b 0.0.0.0:5000 manage:app

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      report-service:
        condition: service_started
    links:
      - report-service

