version: '2.1'

services:

  report-db:
    container_name: report-db
    build: ./project/db
    ports:
      - 5435:5432 # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  report-service:
    container_name: report-service
    build: ./
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@report-db:5432/report_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@report-db:5432/report_test
    depends_on:
      report-db:
        condition: service_healthy
    links:
      - report-db